# Generated by Django 3.2.25 on 2025-10-21 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('happy', '快樂'), ('neutral', '中立'), ('sad', '悲傷'), ('angry', '生氣'), ('surprised', '驚訝'), ('fear', '害怕'), ('disgust', '厭惡'), ('bored', '無聊')], max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
