# Generated by Django 3.2.25 on 2025-11-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0002_alter_emotionrecord_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionrecord',
            name='emotion',
            field=models.CharField(choices=[('frustrated', '挫折'), ('confused', '困惑'), ('bored', '無聊'), ('engaged', '投入'), ('surprised', '驚訝'), ('happy', '喜悅')], max_length=20),
        ),
    ]
