# Generated by Django 3.2.25 on 2026-03-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0003_alter_emotionrecord_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionrecord',
            name='emotion',
            field=models.CharField(choices=[('frustration', '挫折'), ('confusion', '困惑'), ('boredom', '無聊'), ('engagement', '投入'), ('surprise', '驚訝'), ('delight', '喜悅')], max_length=20),
        ),
    ]
