# -*- coding: utf-8 -*-
"""emotion_to_engagement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TsDnfRhwf5-8P_tDtmLitknvEriELDJ3
"""

from typing import List, Tuple, Optional

#六種學習情緒對應參與度分數
EMOTION_TO_ENGAGEMENT = {
    "喜悅": 1.0,
    "投入": 1.0,
    "驚訝": 1.0,
    "無聊": 0.0,
    "困惑": 0.5,
    "挫折": 0.0,
}

FALLBACK_ENGAGEMENT = 0.5  #未知情緒

#情緒字串轉成對應的參與度分數
def map_emotion_to_score(emotion):
    return EMOTION_TO_ENGAGEMENT.get(emotion.strip(), FALLBACK_ENGAGEMENT)

#輸入情緒序列，回傳參與度分數
def compute_engagement(emotions):
    """
    "ema" (指數平滑法)：即時追蹤學習狀態，快速反應「最近」的情緒
    """
    #空序列
    if not emotions:
        return FALLBACK_ENGAGEMENT

    #情緒字串轉成數值分數
    scores = [map_emotion_to_score(e) for e in emotions]

    #if method == "mean":
      #return sum(scores) / len(scores)

    alpha = 0.4  #越大越重視最近的情緒
    ema = scores[0]
    for x in scores[1:]:
        ema = alpha * x + (1 - alpha) * ema

    if ema >= 0.5:
      return "high"
    else:
      return "low"

"""測試"""

emotions_seq = ["喜悅", "困惑", "投入", "喜悅", "挫折", "無聊"]

print("參與度：", compute_engagement(emotions_seq))