# -*- coding: utf-8 -*-
"""loadPromptData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XhaoUVd6MYzFS_C8dfwQXLmojXQpsvJC

實驗資料
"""

from google.colab import drive
drive.mount('/content/drive')

# loadPromptData.py
import pandas as pd
import ast

# === 全域變數 ===
promptExpA = []

def load_experiment_data(csv_path: str, exp_name):
    """
    從 CSV 載入實驗資料，轉換成 list 格式回傳 exp_name。
    每筆格式為 dict：
    {
        "question": str,
        "engagement": str,
        "level": str,
        "materials": list[str]
    }
    """
    df = pd.read_csv(csv_path)

    exp_name = []  # reset

    for _, row in df.iterrows():
        # CSV 裡的「教材 list」是字串，可能像：
        # "教材1","教材2","教材3"
        # 這裡轉換成 list[str]
        raw_materials = row["教材 list"]

        # 確保字串能安全轉成 list
        try:
            # 統一加中括號再 eval，避免分隔問題
            materials = ast.literal_eval("[" + raw_materials + "]")
        except Exception:
            # 如果解析失敗，就直接用逗號切
            materials = [m.strip().strip('"') for m in raw_materials.split(",")]

        entry = {
            "question": row["學生提問"],
            "engagement": row["參與度"],
            "level": row["學習狀態"],
            "materials": materials
        }
        exp_name.append(entry)

    return exp_name


# === 測試用 ===
'''
data_path_A：操弄檢核：確認系統能穩定產生High / Low 兩種預期回覆（語氣、結尾型態、術語層級等）
'''
data_path_A = "/content/drive/MyDrive/專題/程式碼專區/ProgressPal/prompt實驗資料/題庫/linear_data_structure_questions_detailed.csv"
promptExpA = load_experiment_data(data_path_A, promptExpA)

print(f"載入 {len(promptExpA)} 筆資料")
print("第一筆範例：")
print(promptExpA[0])