# -*- coding: utf-8 -*-
"""loadPromptData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XhaoUVd6MYzFS_C8dfwQXLmojXQpsvJC

實驗資料
"""

from google.colab import drive
drive.mount('/content/drive')

# loadPromptData.py
import pandas as pd
import ast

# === 全域變數 ===
PromptExpA = []

def create_list(csv_path: str):
  """
  從 CSV 載入實驗資料，轉換成 list 格式回傳。
  每筆格式為 dict：
  {
      "question": str,
      "engagement": str,
      "level": str,
      "materials": list[str]
  }
  """
  df = pd.read_csv(csv_path)
  exp_list = []

  for _, row in df.iterrows():
      raw_materials = row["教材 list"]
      try:
          materials = ast.literal_eval("[" + raw_materials + "]")
      except Exception:
          materials = [m.strip().strip('"') for m in raw_materials.split(",")]

      entry = {
          "question": row["學生提問"],
          "engagement": row["參與度"],
          "level": row["學習狀態"],
          "materials": materials
      }
      exp_list.append(entry)

  return exp_list

def load_experiment_data():
  '''
  data_path_A：操弄檢核：確認系統能穩定產生High / Low 兩種預期回覆（語氣、結尾型態、術語層級等）
  '''
  global PromptExpA
  data_path_A = "/content/drive/MyDrive/專題/程式碼專區/ProgressPal/prompt實驗資料/題庫/linear_data_structure_questions_detailed.csv"
  PromptExpA = create_list(data_path_A)

if __name__ == "__main__":
  load_experiment_data()
  print(f"載入 {len(PromptExpA)} 筆資料")
  print("第一筆範例：")
  print(PromptExpA[0])
