# Generated by Django 3.2.25 on 2025-10-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlog',
            name='emotion',
        ),
    ]
