# Generated by Django 3.2.25 on 2025-11-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_questionlog_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('mis_student', '資訊領域大學生'), ('normal_student', '非資訊領域大學生')], default='student', max_length=20),
        ),
    ]
