# Generated by Django 3.2.25 on 2025-12-16 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_quizquestion'),
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='total_questions',
            field=models.PositiveIntegerField(default=0, verbose_name='題目總數'),
        ),
        migrations.CreateModel(
            name='QuizResultQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='學生作答')),
                ('is_correct', models.BooleanField(verbose_name='是否正確')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='作答時間')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.quizquestion', verbose_name='題目')),
                ('quiz_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_questions', to='accounts.quizresult', verbose_name='所屬測驗結果')),
            ],
        ),
    ]
