# Generated by Django 3.2.25 on 2025-12-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20251216_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='unit_code',
        ),
        migrations.RemoveField(
            model_name='quizresultquestion',
            name='answered_at',
        ),
    ]
