# Generated by Django 3.2.25 on 2025-12-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20251216_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='total_questions',
        ),
    ]
