# Generated by Django 3.2.25 on 2026-01-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_quizresult_total_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionlog',
            old_name='question',
            new_name='stu_input',
        ),
        migrations.AddField(
            model_name='questionlog',
            name='system_question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionlog',
            name='type',
            field=models.CharField(choices=[('question', '學生提問'), ('answer_extend_question', '學生回應引導提問')], default='question', max_length=30),
        ),
    ]
