# Generated by Django 3.2.25 on 2026-04-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20260123_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('high_prior_student', '高先備知識學生'), ('low_prior_student', '低先備知識學生')], default='student', max_length=20),
        ),
    ]
