# Generated by Django 3.2.25 on 2026-04-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlog',
            name='hint_is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('high_prior_student', 'A'), ('low_prior_student', 'B')], default='student', max_length=20),
        ),
    ]
