# Generated by Django 3.2.25 on 2026-06-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20260425_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlog',
            name='click_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
