# Generated by Django 3.2.25 on 2026-05-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20260425_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('high_prior_student', '資訊領域學生'), ('low_prior_student', '非資訊領域學生')], default='student', max_length=20),
        ),
    ]
