# Generated by Django 3.2.25 on 2026-05-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('high_prior_student', '高先備知識學生'), ('low_prior_student', '低先備知識學生')], default='student', max_length=20),
        ),
    ]
