# Generated by Django 3.2.25 on 2025-10-21 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField(unique=True, verbose_name='章節數字')),
                ('title', models.CharField(max_length=50, verbose_name='章節標題')),
            ],
            options={
                'ordering': ['chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=10, verbose_name='單元編號')),
                ('title', models.CharField(max_length=50, verbose_name='單元標題')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='learning.chapter', verbose_name='所屬章節')),
            ],
            options={
                'ordering': ['unit_number'],
                'unique_together': {('chapter', 'unit_number')},
            },
        ),
    ]
