# Generated by Django 3.2.25 on 2025-12-10 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', '簡單'), ('medium', '中等'), ('hard', '困難')], max_length=10, verbose_name='難度')),
                ('question', models.TextField(verbose_name='題目內容')),
                ('option_a', models.TextField(verbose_name='選項 A')),
                ('option_b', models.TextField(verbose_name='選項 B')),
                ('option_c', models.TextField(verbose_name='選項 C')),
                ('option_d', models.TextField(verbose_name='選項 D')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='正確答案')),
                ('explanation', models.TextField(verbose_name='解析')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.chapter', verbose_name='所屬章節')),
            ],
            options={
                'verbose_name': '測驗題目',
                'verbose_name_plural': '測驗題目',
            },
        ),
    ]
