# Generated by Django 3.2.25 on 2026-04-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_quizquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.PositiveIntegerField(verbose_name='單元編號'),
        ),
    ]
